# Generated by Django 5.1.3 on 2024-11-20 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=10)),
                ('arrival', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('departureTime', models.TimeField()),
                ('arrivalTime', models.TimeField()),
                ('seatNumber', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
