# Generated by Django 5.1.3 on 2024-11-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0002_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seatNumber',
            field=models.CharField(max_length=20),
        ),
    ]
