# Generated by Django 5.1.3 on 2024-11-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0002_alter_reservation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('bus_class', models.CharField(max_length=50)),
                ('seats_available', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Bus Schedule',
                'verbose_name_plural': 'Bus Schedules',
                'ordering': ['departure_time'],
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seatNumber',
            field=models.CharField(max_length=20),
        ),
    ]
