# Generated by Django 5.1.3 on 2024-11-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_reservation', '0008_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
    ]
